### ISSUE TITLE
Migrate from npm to pnpm

### ISSUE THREAD

**Issue by stefanleminh** [AkrosAG/Akros-Marketplace#79]
As a developer I want to replace npm in both the main project and the webcomponents with [pnpm](https://pnpm.io) in order to increase build speed and disk efficiency locally and on the pipeline.
If it's easy, it might be worth it to implement [workspaces](https://pnpm.io/workspaces)? Should be investigated.

- [x] AC1: The pipeline and build scripts work the same as they did before.

DoD
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- ~~Integration test is done ( if applicable)~~
- [x] Non-functional requirements are met
- [x] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented

Tasks:
- [x] Migrate locally from npm to pnpm
- [x] Adjust the Github Actions

**Comment by pestadieu** [comment]
See the branch: 79-migrate-to-pnpm

**Comment by Ayerbe88** [comment]
The merge of pnpm was performed on 28.11.2022 and changed were then reverted on 12.12.2022 due to several problems. There is an incopatibility with the Msal service that frontend uses and further complications is the build process and docker images generation. The branch with all the content of pnpm remains in the repository in case it is ever wanted to work on it again.

**Comment by akrguda** [comment]
As we discussed it in the planing meeting at 13.12.2022 we close this ticket because of the descibed problems (see comment from Ayerbe88). There are to many problmens to use pnpm.
