### ISSUE TITLE
How to implement image upload and thumbnail preview

### ISSUE THREAD

**Issue by stefanleminh** [AkrosAG/Akros-Marketplace#84]
We have to research how to properly upload images from the user.
Apparently the way to best store images is not to save them in the database but save a pointer (i.e. URL) in the database and store the image itself on a hoster. Since we're on the Azure platform, [this article](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-upload-process-images?tabs=dotnet%2Cazure-powershell) might prove useful.

The following points also need to be researched:
- How to create a low-res thumbnail from the uploaded images
- How to enforce a 5:3 aspect ratio (do we need to actually crop images and save the cropped images or is it maybe better to only crop via css with object-fit or other?)

The results should be documented as a comment here and a ticket should be created (unless it already exists).

Timeboxed: 1/2 Day

**Comment by Ayerbe88** [comment]
**Image storage and Backend services**

As stated in the description of the task, since the MP (Market Place) project already makes use of Azure to host the application, it would be most convenient to make use of the Azure Blob Storage feature, which is specifically designed to store documents, images and media files. 

In order to do this an storage account has to be set in Azure, followed by creating a container with public access level set to Blob. After set up, there are several quickstarts, tutorials and examples that can be used to create the service to manage Blobs, connect to the storage container, upload/download. Since this will be independent of the main API, there is no reason why it must be done in java, nevertheless if chosen to implement in java the [following guide](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java?tabs=powershell%2Cenvironment-variable-windows) can be used.

Along with a wide [set of samples](https://docs.microsoft.com/en-us/azure/storage/common/storage-samples-java?toc=/azure/storage/blobs/toc.json) to do all operations that will be needed.

The processing of the uploaded images won't be necessary for the purpose of MP, if ever needed see section for creating the [computer vision service](https://docs.microsoft.com/en-us/azure/storage/blobs/blob-upload-function-trigger?tabs=azure-portal#create-the-computer-vision-service)


**Frontend**

From the frontend side  can be used [ng2-file-upload](https://valor-software.com/ng2-file-upload/), which provides functionality to perform the images upload and manage them with things like drag and drop area, list of uploads to be performed with option to cancel and such.

![image](https://user-images.githubusercontent.com/5686587/164227092-7e689adc-c106-4782-b2ab-05edcd092b94.png)

Otherwise it can be implemented without further libraries as for example shown in this [tutorial](https://www.geeksforgeeks.org/angular-file-upload/)


Also a tutorial for doing the same [Vue3 image upload](https://www.smashingmagazine.com/2022/03/drag-drop-file-uploader-vuejs-3/) with drag and drop included in Vue3

In either case Styles will have to be implemented, or used from external libraries, in order to present the images to be uploaded and later same component to be used to display images in the detail view. There is a great amount of samples available to use, it's a matter of deciding how we want to present the images. A suggestion for the detail view, and adaptable to the creation view, would be to use a carousel showing the active image (without cycling) and flexible horizontal list of all the images in small thumbnails. [See link for example with bootstrap](https://bbbootstrap.com/snippets/carousel-slider-thumbnails-25493000)

**Comment by Ayerbe88** [comment]
- How to create a low-res thumbnail from the uploaded images

Can be achieved using one of the examples provided in the previous comment

- How to enforce a 5:3 aspect ratio (do we need to actually crop images and save the cropped images or is it maybe better to only crop via css with object-fit or other?)

I don't think we need to crop images ourselves, object-fit with "cover" should do the trick, and the user can see how it will look in the thumbnails thought the application and there decide if use or not that image.

[object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
